# Generated by Django 2.2.1 on 2019-09-12 06:59

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companys',
            name='introduce',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='companys',
            name='personnel',
            field=models.IntegerField(default=1, verbose_name='人员'),
        ),
        migrations.AlterField(
            model_name='job',
            name='describe',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='描述'),
        ),
    ]
