# Generated by Django 2.2.1 on 2019-10-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.IntegerField(choices=[(1, '不限'), (2, '大专'), (3, '本科'), (4, '硕士')], verbose_name='学历'),
        ),
    ]
