# Generated by Django 2.2.1 on 2019-09-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_auto_20190911_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaInfo',
        ),
    ]
