# Generated by Django 2.2.1 on 2019-09-12 06:59

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumejob',
            name='function',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='职能'),
        ),
        migrations.AlterField(
            model_name='resumejob',
            name='self_evaluation',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='自我评价'),
        ),
        migrations.AlterField(
            model_name='resumeprojectexperience',
            name='project_description',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='resumeprojectexperience',
            name='responsibility_description',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='责任描述'),
        ),
        migrations.AlterField(
            model_name='resumeworking',
            name='job_description',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='工作描述'),
        ),
    ]
