# Generated by Django 2.2.1 on 2019-09-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
