# Generated by Django 2.2.1 on 2019-10-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(upload_to='users/', verbose_name='头像'),
        ),
    ]
