# Generated by Django 2.2.1 on 2019-09-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='area',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='用户所在区域'),
        ),
    ]
